# 1 Import the numpy and check version

In [103]:
import numpy as np

In [104]:
print(np.__version__)

1.19.4


# 2 null vector of size 10 

In [105]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. find the memory size of any array

In [106]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# 4. null vector of size 10 but the fifth value which is 1

In [107]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 5. vector with values ranging from 10 to 49

In [108]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 6. Reverse a vector

In [109]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 7. Create a 3x3 matrix with values ranging from 0 to 8

In [110]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 8. non-zero elements from [1,2,0,0,4,0]

In [111]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


# 9. 3x3 identity 

In [112]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 10. 3x3x3 array with random values

In [113]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.31006071 0.77321738 0.34577806]
  [0.2742547  0.48489235 0.30476142]
  [0.98898752 0.34828146 0.10183929]]

 [[0.81981725 0.42231202 0.91664087]
  [0.44364799 0.38040463 0.29552878]
  [0.74276704 0.03819644 0.59896997]]

 [[0.52510621 0.93356346 0.89501599]
  [0.45093581 0.92616155 0.36004233]
  [0.1048077  0.58485703 0.65176056]]]


# 11.  10x10 array with random values and find the minimum and maximum values

In [114]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.008120538296401913 0.9882805148832421


# 12. random vector of size 30 and find the mean value

In [115]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.48935224066991584


# 13.  5x5 matrix with values 1,2,3,4 just below the diagonal

In [116]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 14. 8x8 matrix and fill it with a checkerboard pattern

In [117]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 15. np.unravel_index

In [118]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


# 16. checkerboard 8x8 matrix using the tile function

In [119]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 17. 5x5 random matrix

In [120]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.48015831 -1.43570965  0.9421477  -0.78760746  0.39640908]
 [ 0.62435139  1.39613166 -1.08518079 -1.61115612 -1.20343205]
 [ 1.31217788  0.53633301 -0.49130669  0.70531524 -1.16615107]
 [ 0.34469693  1.36222758 -1.09296547  0.93788788 -0.57355973]
 [ 1.42256209 -0.99291551 -0.29178472 -0.14022472  1.37191186]]


# 18. np.intersect1d

In [130]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 4 8]


# 19. np.datetime64, np.timedelta64

In [131]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

# 20. np.arange

In [132]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 21. np.floor

In [133]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 8. 6. 2. 6. 7. 0. 7. 4. 6.]
[4. 8. 6. 2. 6. 7. 0. 7. 4. 6.]
[4. 8. 6. 2. 6. 7. 0. 7. 4. 6.]
[4 8 6 2 6 7 0 7 4 6]
[4. 8. 6. 2. 6. 7. 0. 7. 4. 6.]


# 22.  np.arange

In [134]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 23. np.linspace

In [135]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 24. sort

In [136]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.16574942 0.20160802 0.21067399 0.21164858 0.3078682  0.37645919
 0.42666913 0.60813328 0.61396789 0.83918315]


# 25. np.add.reduce

In [137]:
Z = np.arange(10)
np.add.reduce(Z)

45

# 26. flags.writeable

In [138]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

# 27. argmax

In [139]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.67111061 0.01424431 0.25508287 0.20143499 0.45004382 0.45765793
 0.         0.64999232 0.63695853 0.06388024]


# 28. argmin

In [140]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

52


# 29. 2D array has null columns

In [141]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


# 30. np.abs

In [142]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5630666491987657


# 31. np.nditer

In [143]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 32. np.bincount

In [144]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 4. 2. 5. 4. 3. 4. 2. 3.]


# 33. add

In [145]:
np.add.at(Z, I, 1)
print(Z)

[3. 1. 7. 3. 9. 7. 5. 7. 3. 5.]


# 34. np.bincount

In [146]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 35. np.repeat

In [147]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# 36. np.cumsum

In [148]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# 37. np.argsort

In [149]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 38.  np.argpartition

In [150]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9998 9997 9996 9999 9995]


# 39. np.where

In [151]:
results = np.array([30,50,80,15,25,90,95,63])
np.where(results>40,"Pass", "Fail")

array(['Fail', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Pass', 'Pass'],
      dtype='<U4')

#  40. mean

In [152]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
A.mean()

5.5

# 41. sum

In [153]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
A.sum()

55

# 42. sort

In [157]:
c = np.array([1,8,7,2,6,7,8,4,1,6,3,88,5,5,5,])
c.sort()
print(c)

[ 1  1  2  3  4  5  5  5  6  6  7  7  8  8 88]


# 43. arange

In [158]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9999 9998 9996 9995]


# 44.random

In [159]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.84 s ± 38.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
329 ms ± 9.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
227 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 45. ones

In [160]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 46.unravel

In [161]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


# 47. tile

In [162]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 48. dot

In [163]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 49.  random

In [164]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 4 5 6 8]


# 50. arange

In [165]:
Z = np.arange('2020-07', '2020-08', dtype='datetime64[D]')
print(Z)

['2020-07-01' '2020-07-02' '2020-07-03' '2020-07-04' '2020-07-05'
 '2020-07-06' '2020-07-07' '2020-07-08' '2020-07-09' '2020-07-10'
 '2020-07-11' '2020-07-12' '2020-07-13' '2020-07-14' '2020-07-15'
 '2020-07-16' '2020-07-17' '2020-07-18' '2020-07-19' '2020-07-20'
 '2020-07-21' '2020-07-22' '2020-07-23' '2020-07-24' '2020-07-25'
 '2020-07-26' '2020-07-27' '2020-07-28' '2020-07-29' '2020-07-30'
 '2020-07-31']
